/*
 * Experiment -- Generate a datastructure that holds harmonic oscillator
 *               points for a perfect oscillator
 *
 * It importantly doesn't depend on anything else so that it can be compiled
 * and run as part of building everything.
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>
#include <ctype.h>
#include <string.h>

/* The amplitude of choice */
#define AMPLITUDE	16384
int16_t *octant_table;
int octant_elements;

void
gen_octant() {
	int i;
	
	octant_elements = (int) ((double) AMPLITUDE * sqrt(2.0)/2.0 + 0.5)
	printf("Generate octant table with %d entries.\n", size);
	octant_table = calloc(octant_elements, sizeof(int16_t));
	if (! octant_table) {
		fprintf(stderr, "Error allocating octant table.\n");
		exit(1);
	}

	for (int k = 0; k < octant_elements; k++) {
		double r = sqrt(AMPLITUDE * AMPLITUDE - k * k);
		octant_table[k] = (int16_t)(r + 0.5);
	}
	printf("done.\n");
}

int
main(int argc, char *argv[]) {

	double rad, cur_rad;
	int16_t px, py;
	double ea, ex, ey, dx, dy;
	double max_ea, max_ex, max_ey;
	double min_ea, min_ex, min_ey;
	int num_refs = 1;
	double len;
	int gen_code = 0;
	FILE *of;

	max_ea = max_ex = max_ey = 0;
	min_ea = min_ex = min_ey = 0;

	/*
	 * The smallest radian that would cause the X,Y position to change, is
	 * one 'unit' up, and full length long 
	 */
	len = sqrt(AMPLITUDE*AMPLITUDE + 1);
	// printf("Length of the hyp of our triangle: %f\n", len);
	rad = asin(1.0/len);

	if (strstr(argv[1], ".c") != NULL) {
		gen_code = 1;
	} else if (strstr(argv[1],".h") != NULL) {
		gen_code = 0;
	} else {
		fprintf(stderr, "Must specify a .c file or .h file on the command line\n");
		exit(1);
	}

	of = fopen(argv[1], "w");
	if (gen_code) {
		fprintf(of,
			"/*\n"
			" * %s - data structure holding coordinates for a circle\n"
			" * **** GENERATED BY perfect_osc.c DO NOT EDIT ****\n"
			" */\n"
			"#include <dsp/ho_refs.h>\n\n"
			"ref_t refs[] = {\n", argv[1]);
			fprintf(of, "    { %10.7f, %5d, %5d },\n", 0.0, 0, AMPLITUDE);
	} else {
		fprintf(of,
			"/*\n"
			" * Harmonic Oscillator Definitions\n"
			" * **** GENERATED BY perfect_osc.c DO NOT EDIT ****\n"
			" */\n\n"
			"#pragma once\n"
			"#include <stdint.h>\n"
			"#define REFS_MIN_RADIAN %10.8f\n\n", rad);
		fprintf(of,
			"typedef struct {\n"
			"    double radians;\n"
   			"    int16_t x;\n"
			"    int16_t y;\n"
			"} ref_t;\n\n"
		);
		fprintf(of,
			"extern int16_t octant_table[11586];\n");
	}
	px = 0;
	py = 16384;
	cur_rad = 0;
	num_refs = 1;
	for (int k = 1; k < octant_elements; k++) {
		int16_t xi, yi;
		double rad;

		xi = octant_table[k];
		yi = k;
		rad = atan2((double) yi, (double) xi);

		/* actual radius and actual angle */
		double act_r = sqrt(xi * xi + yi * yi);
		double act_a = asin(xi / act_r);

		if (gen_code) {
xxx
			fprintf(of, "    { %10.7f, %5d, %5d },", rad, xi, yi);
			ex = x - xi;		// Fractional part of X
			ey = y - yi;		// Fractional part of Y
			ea = AMPLITUDE - act_r;		// Fractional part of amplitude.
			fprintf(of, "// [ %d%c] (Ae, Xe, Ye) => %6.5f, %6.5f, %6.5f\n",
				num_refs, (num_refs != xi) ? '*' : ' ', ea, ex, ey);
			max_ex = (ex >= max_ex) ? ex : max_ex;
			max_ey = (ey >= max_ey) ? ey : max_ey;
			max_ea = (ea >= max_ea) ? ea : max_ea;
			min_ex = (ex <= min_ex) ? ex : min_ex;
			min_ey = (ey <= min_ex) ? ey : min_ey;
			min_ea = (ea <= min_ea) ? ea : min_ea;

		}
		num_refs++;
	}
	if (gen_code) {
		fprintf(of, "};\n");
		fprintf(of, "/*\n"
					" * Error limits: \n"
					" *    min/max X error : %6.5f / %6.5f\n"
					" *    min/max Y error : %6.5f / %6.5f\n"
					" *    min/max A error : %6.5f / %6.5f\n"
					" */\n",
					min_ex, max_ex, min_ey, max_ey, min_ea, max_ea);
	} else {
		fprintf(of, 
			"#define REFS_MAX_REF	%d\n"
			"extern ref_t refs[REFS_MAX_REF];\n", num_refs);
	}
	if (gen_code) {
		fprintf(of, "int16_t octant_table[] = {\n\t");
		for (int i = 0; i < 11586; i++) {
			double r = sqrt(AMPLITUDE * AMPLITUDE - i * i);
			int16_t ri = (int16_t)(r + 0.5);
			fprintf(of, "%6d, ", ri);
			if (((i + 1) % 8) == 0) {
				fprintf(of, "\n\t");
			}
		}
		fprintf(of,"\n};\n");
	}
	fclose(of);
}
